"use client";

import { candidatosService } from "@/app/lib/firestore-service";
import type { Candidato } from "@/app/lib/types";

// Perfiles de candidatos colombianos representativos para demo
const PERFILES: Omit<Candidato, "createdAt" | "updatedAt">[] = [
  {
    uid: "demo_candidato_01",
    nombre: "Valentina Torres Mora",
    email: "v.torres@demo.talentoya.co",
    telefono: "314 801 2233",
    ciudad: "Bogotá",
    titulo: "Desarrolladora Frontend",
    resumen: "4 años de experiencia en desarrollo web moderno. Domino React, Next.js y Tailwind. Apasionada por UX y accesibilidad.",
    habilidades: [
      { nombre: "React", nivel: 90 },
      { nombre: "Next.js", nivel: 85 },
      { nombre: "Tailwind CSS", nivel: 80 },
      { nombre: "TypeScript", nivel: 75 },
      { nombre: "Git", nivel: 85 },
    ],
    experiencia: [
      {
        empresa: "Soluciones Tech SAS",
        cargo: "Desarrolladora Frontend",
        desde: "2021-03",
        hasta: "",
        actual: true,
        descripcion: "Desarrollo de dashboards y apps web para clientes PyME.",
      },
      {
        empresa: "AgenciaWeb Colombia",
        cargo: "Desarrolladora Junior",
        desde: "2019-06",
        hasta: "2021-02",
        actual: false,
      },
    ],
    educacion: [
      {
        institucion: "Universidad Nacional de Colombia",
        titulo: "Ingeniería de Sistemas",
        desde: "2015",
        hasta: "2020",
      },
    ],
    idiomas: [{ idioma: "Inglés", nivel: "intermedio" }],
    certificaciones: [
      { nombre: "Meta Frontend Developer", institucion: "Coursera", año: 2022 },
    ],
    salarioEsperado: 4500000,
    disponibilidad: "15_dias",
    modalidadPreferida: "hibrido",
    verificado: true,
    profileCompleted: true,
  },
  {
    uid: "demo_candidato_02",
    nombre: "Carlos Andrés Ríos",
    email: "c.rios@demo.talentoya.co",
    telefono: "301 234 5678",
    ciudad: "Medellín",
    titulo: "Técnico Electromecánico",
    resumen: "6 años en mantenimiento industrial de maquinaria pesada. Especialista en PLCs Siemens y Allen Bradley.",
    habilidades: [
      { nombre: "Mantenimiento Preventivo", nivel: 95 },
      { nombre: "PLC", nivel: 85 },
      { nombre: "Seguridad Industrial", nivel: 90 },
      { nombre: "Interpretación de Planos", nivel: 80 },
      { nombre: "Liderazgo de Equipos", nivel: 70 },
    ],
    experiencia: [
      {
        empresa: "Industrias Metálicas S.A.",
        cargo: "Técnico de Mantenimiento Senior",
        desde: "2019-01",
        hasta: "",
        actual: true,
      },
      {
        empresa: "Manufacturas del Valle",
        cargo: "Técnico Electromecánico",
        desde: "2017-06",
        hasta: "2018-12",
        actual: false,
      },
    ],
    educacion: [
      {
        institucion: "SENA Medellín",
        titulo: "Técnico en Electromecánica",
        desde: "2014",
        hasta: "2016",
      },
    ],
    idiomas: [],
    certificaciones: [
      { nombre: "Trabajo en Alturas", institucion: "SENA", año: 2023 },
      { nombre: "Seguridad en Espacios Confinados", institucion: "ARL Sura", año: 2022 },
    ],
    salarioEsperado: 3200000,
    disponibilidad: "inmediata",
    modalidadPreferida: "presencial",
    verificado: true,
    profileCompleted: true,
  },
  {
    uid: "demo_candidato_03",
    nombre: "Laura Sofía Pedraza",
    email: "l.pedraza@demo.talentoya.co",
    telefono: "310 987 6543",
    ciudad: "Cali",
    titulo: "Ejecutiva de Ventas B2C",
    resumen: "5 años en ventas directas y televentas. Top performer durante 3 años consecutivos. Especialista en cierre de negocios.",
    habilidades: [
      { nombre: "Ventas B2C", nivel: 95 },
      { nombre: "Atención al Cliente", nivel: 90 },
      { nombre: "CRM Salesforce", nivel: 75 },
      { nombre: "Comunicación Asertiva", nivel: 88 },
      { nombre: "Negociación", nivel: 85 },
    ],
    experiencia: [
      {
        empresa: "Claro Colombia",
        cargo: "Ejecutiva de Ventas",
        desde: "2020-03",
        hasta: "",
        actual: true,
      },
      {
        empresa: "Multiactive S.A.S",
        cargo: "Asesora Comercial",
        desde: "2018-08",
        hasta: "2020-02",
        actual: false,
      },
    ],
    educacion: [
      {
        institucion: "Universidad del Valle",
        titulo: "Administración de Empresas",
        desde: "2013",
        hasta: "2018",
      },
    ],
    idiomas: [{ idioma: "Inglés", nivel: "basico" }],
    certificaciones: [],
    salarioEsperado: 2800000,
    disponibilidad: "inmediata",
    modalidadPreferida: "presencial",
    verificado: true,
    profileCompleted: true,
  },
  {
    uid: "demo_candidato_04",
    nombre: "Jhon Sebastián Morales",
    email: "j.morales@demo.talentoya.co",
    telefono: "315 654 3210",
    ciudad: "Bogotá",
    titulo: "Auxiliar Administrativo",
    resumen: "3 años gestionando procesos administrativos en empresas del sector salud. Excelente manejo de Excel y herramientas ofimáticas.",
    habilidades: [
      { nombre: "Excel Básico", nivel: 85 },
      { nombre: "Gestión de tiempo", nivel: 80 },
      { nombre: "Trabajo en equipo", nivel: 90 },
      { nombre: "Comunicación Asertiva", nivel: 78 },
      { nombre: "Servicio al cliente", nivel: 82 },
    ],
    experiencia: [
      {
        empresa: "Clínica Santa Fe",
        cargo: "Auxiliar Administrativo",
        desde: "2021-04",
        hasta: "",
        actual: true,
      },
    ],
    educacion: [
      {
        institucion: "Politécnico Grancolombiano",
        titulo: "Técnico en Administración Empresarial",
        desde: "2018",
        hasta: "2020",
      },
    ],
    idiomas: [],
    certificaciones: [],
    salarioEsperado: 1700000,
    disponibilidad: "30_dias",
    modalidadPreferida: "presencial",
    verificado: false,
    profileCompleted: true,
  },
  {
    uid: "demo_candidato_05",
    nombre: "Isabella Restrepo Cadavid",
    email: "i.restrepo@demo.talentoya.co",
    telefono: "313 222 1111",
    ciudad: "Medellín",
    titulo: "Cocinera Profesional — Pastelería y Panadería",
    resumen: "8 años en cocina profesional con especialización en repostería francesa. Experiencia en hoteles 5 estrellas y restaurantes de alta cocina.",
    habilidades: [
      { nombre: "Pastelería y Repostería", nivel: 95 },
      { nombre: "Panadería Artesanal", nivel: 88 },
      { nombre: "Manejo de Inventario", nivel: 70 },
      { nombre: "Control de calidad", nivel: 80 },
      { nombre: "Trabajo en equipo", nivel: 85 },
    ],
    experiencia: [
      {
        empresa: "Hotel Intercontinental Medellín",
        cargo: "Pastry Chef",
        desde: "2019-06",
        hasta: "",
        actual: true,
      },
      {
        empresa: "Restaurante El Cielo",
        cargo: "Asistente de Pastelería",
        desde: "2015-01",
        hasta: "2019-05",
        actual: false,
      },
    ],
    educacion: [
      {
        institucion: "Le Cordon Bleu Bogotá",
        titulo: "Diploma en Arte Culinario",
        desde: "2013",
        hasta: "2015",
      },
    ],
    idiomas: [{ idioma: "Inglés", nivel: "intermedio" }, { idioma: "Francés", nivel: "basico" }],
    certificaciones: [
      { nombre: "Manipulación de Alimentos", institucion: "INVIMA", año: 2023 },
    ],
    salarioEsperado: 2500000,
    disponibilidad: "30_dias",
    modalidadPreferida: "presencial",
    verificado: true,
    profileCompleted: true,
  },
  {
    uid: "demo_candidato_06",
    nombre: "Daniel Felipe Gutiérrez",
    email: "d.gutierrez@demo.talentoya.co",
    telefono: "320 333 4444",
    ciudad: "Barranquilla",
    titulo: "Operario de Producción / Logística",
    resumen: "Sin experiencia formal, recién egresado de bachillerato. Muy motivado, disponibilidad inmediata y residente en zona industrial.",
    habilidades: [
      { nombre: "Trabajo en equipo", nivel: 80 },
      { nombre: "Atención al Cliente", nivel: 65 },
      { nombre: "Resolución de problemas", nivel: 70 },
    ],
    experiencia: [],
    educacion: [
      {
        institucion: "Colegio Distrital La Paz",
        titulo: "Bachiller",
        desde: "2017",
        hasta: "2023",
      },
    ],
    idiomas: [],
    certificaciones: [],
    salarioEsperado: 1300000,
    disponibilidad: "inmediata",
    modalidadPreferida: "presencial",
    verificado: false,
    profileCompleted: true,
  },
  {
    uid: "demo_candidato_07",
    nombre: "Mariana Ospina Vélez",
    email: "m.ospina@demo.talentoya.co",
    telefono: "317 555 7788",
    ciudad: "Bogotá",
    titulo: "Community Manager / Marketing Digital",
    resumen: "3 años gestionando redes sociales para marcas de moda y lifestyle. Expertise en Meta Ads y estrategia de contenidos.",
    habilidades: [
      { nombre: "Redes Sociales", nivel: 92 },
      { nombre: "Meta Ads", nivel: 85 },
      { nombre: "Canva / Diseño", nivel: 80 },
      { nombre: "Comunicación Asertiva", nivel: 88 },
      { nombre: "Resolución de problemas", nivel: 75 },
    ],
    experiencia: [
      {
        empresa: "Studio 73 Moda",
        cargo: "Community Manager",
        desde: "2022-01",
        hasta: "",
        actual: true,
      },
      {
        empresa: "Agencia Pixel",
        cargo: "Asistente Digital",
        desde: "2021-01",
        hasta: "2021-12",
        actual: false,
      },
    ],
    educacion: [
      {
        institucion: "Uniminuto",
        titulo: "Comunicación Social y Periodismo",
        desde: "2017",
        hasta: "2021",
      },
    ],
    idiomas: [{ idioma: "Inglés", nivel: "avanzado" }],
    certificaciones: [
      { nombre: "Meta Certified Digital Marketing Associate", institucion: "Meta", año: 2023 },
    ],
    salarioEsperado: 2200000,
    disponibilidad: "15_dias",
    modalidadPreferida: "remoto",
    verificado: true,
    profileCompleted: true,
  },
  {
    uid: "demo_candidato_08",
    nombre: "Andrés Felipe Castaño",
    email: "a.castano@demo.talentoya.co",
    telefono: "312 900 1122",
    ciudad: "Bogotá",
    titulo: "Ingeniero de Sistemas / Backend Developer",
    resumen: "Desarrollador backend con 5 años en Python y Node.js. Experiencia en arquitectura de microservicios y despliegue en AWS.",
    habilidades: [
      { nombre: "Python", nivel: 90 },
      { nombre: "Node.js", nivel: 82 },
      { nombre: "Docker", nivel: 78 },
      { nombre: "AWS", nivel: 75 },
      { nombre: "Resolución de problemas", nivel: 92 },
      { nombre: "Git", nivel: 88 },
    ],
    experiencia: [
      {
        empresa: "Bancolombia",
        cargo: "Desarrollador Backend",
        desde: "2020-07",
        hasta: "",
        actual: true,
      },
      {
        empresa: "Startup Fintech",
        cargo: "Backend Junior",
        desde: "2018-09",
        hasta: "2020-06",
        actual: false,
      },
    ],
    educacion: [
      {
        institucion: "Universidad de los Andes",
        titulo: "Ingeniería de Sistemas",
        desde: "2013",
        hasta: "2018",
      },
    ],
    idiomas: [{ idioma: "Inglés", nivel: "avanzado" }],
    certificaciones: [
      { nombre: "AWS Solutions Architect", institucion: "Amazon", año: 2023 },
    ],
    salarioEsperado: 6500000,
    disponibilidad: "30_dias",
    modalidadPreferida: "remoto",
    verificado: true,
    profileCompleted: true,
  },
  {
    uid: "demo_candidato_09",
    nombre: "Tatiana González Araujo",
    email: "t.gonzalez@demo.talentoya.co",
    telefono: "319 444 5566",
    ciudad: "Cartagena",
    titulo: "Coordinadora de Logística y Bodega",
    resumen: "7 años en coordinación logística en puertos y centros de distribución. Manejo de WMS y control de inventarios.",
    habilidades: [
      { nombre: "Manejo de Inventario", nivel: 95 },
      { nombre: "Liderazgo de Equipos", nivel: 85 },
      { nombre: "Excel Básico", nivel: 88 },
      { nombre: "Gestión de tiempo", nivel: 90 },
      { nombre: "Comunicación Asertiva", nivel: 82 },
    ],
    experiencia: [
      {
        empresa: "Puerto de Cartagena",
        cargo: "Coordinadora de Operaciones",
        desde: "2018-02",
        hasta: "",
        actual: true,
      },
      {
        empresa: "DHL Colombia",
        cargo: "Auxiliar de Bodega Senior",
        desde: "2016-01",
        hasta: "2018-01",
        actual: false,
      },
    ],
    educacion: [
      {
        institucion: "Universidad de Cartagena",
        titulo: "Administración de Empresas",
        desde: "2011",
        hasta: "2015",
      },
    ],
    idiomas: [{ idioma: "Inglés", nivel: "intermedio" }],
    certificaciones: [
      { nombre: "Diploma en Logística Internacional", institucion: "Cámara de Comercio", año: 2020 },
    ],
    salarioEsperado: 3500000,
    disponibilidad: "15_dias",
    modalidadPreferida: "presencial",
    verificado: true,
    profileCompleted: true,
  },
  {
    uid: "demo_candidato_10",
    nombre: "Santiago Muñoz Herrera",
    email: "s.munoz@demo.talentoya.co",
    telefono: "316 777 8899",
    ciudad: "Pereira",
    titulo: "Contador Público / Finanzas",
    resumen: "Contador con énfasis en NIIF y tributación colombiana. Experiencia en empresas comerciales y de servicios con facturación >$10 MM/mes.",
    habilidades: [
      { nombre: "Contabilidad NIIF", nivel: 92 },
      { nombre: "Excel Básico", nivel: 90 },
      { nombre: "SIIGO / Alegra", nivel: 85 },
      { nombre: "Gestión de tiempo", nivel: 80 },
      { nombre: "Trabajo en equipo", nivel: 75 },
    ],
    experiencia: [
      {
        empresa: "Confecciones Punto S.A.S",
        cargo: "Contador",
        desde: "2020-01",
        hasta: "",
        actual: true,
      },
      {
        empresa: "Asesorías Tributarias del Eje",
        cargo: "Asistente Contable",
        desde: "2017-06",
        hasta: "2019-12",
        actual: false,
      },
    ],
    educacion: [
      {
        institucion: "Universidad Libre Pereira",
        titulo: "Contador Público",
        desde: "2012",
        hasta: "2017",
      },
    ],
    idiomas: [],
    certificaciones: [
      { nombre: "Especialización en NIIF para PyMES", institucion: "INCP", año: 2021 },
    ],
    salarioEsperado: 3000000,
    disponibilidad: "inmediata",
    modalidadPreferida: "hibrido",
    verificado: true,
    profileCompleted: true,
  },
];

export async function seedCandidatosDemo(): Promise<number> {
  const saves = PERFILES.map(p =>
    candidatosService.set(p.uid, p as Candidato)
  );
  await Promise.all(saves);
  return PERFILES.length;
}
